# -*- coding: utf-8 -*-
"""TGAA2 condensed Court Record captions (the 96 heavy: game_scale < 0.90).

Condensed from Capcom's official Chronicles wording per the TGAA1 rules:
names/spellings/terminology kept, first person kept, hedges kept (supposedly,
appears, it seems, apparently, claims, ostensibly, alleged, believed), jokes
and catchphrases kept (fish and chips, souls damned one way or another),
measurements and cross-references kept. Scarlet v2.1.0 consulted only for what
is cuttable -- its names differ throughout, so no wording is borrowed from it.
cast200_00_c adopts senyarom's own translation/court-record-en.jsonl entry.

ACCEPTED_LOSSES documents facts dropped for width whose information survives in
a sibling caption or is contextually obvious; the review page flags them.
"""

ACCEPTED_LOSSES = {
 'cast032_00_c': "A judicial assistant. The Supreme Court forbids women, so today I'm a lawyer disguised as a male student.",
 'cast104_01_c': "university name (kept in cast104_00_c and cast101_00_c)",
 'cast162_00_c': "'Empire of Japan' -> 'Japanese'",
 'cast201_00_c': "'visiting professor' title (kept in cast900_00_c)",
 'cast255_00_c': "A visiting student to Britain, back home after bad luck with the law. Now a successful author – and a witness.",
 'cast326_00_c': "Governor of Barclay Prison. It seems he and Professor Mikotoba were friends during the latter's studies in Britain.",
 'cast900_00_c': "university name (kept in cast101_00_c/cast104_00_c)",
 'item4_09_01_c': "'Fresno Street' (kept in item4_07_02_c)",
 'item5_13_02_c': "'SS Grouse' (kept in item5_17_01_c)",
 'item5_18_01_c': "Taken in the Great Waterloo Hotel foyer on the morning Professor Mikotoba and Judge Jigoku arrived in London.",
 'cast230_01_c': "full machine name (kept in cast230_00_c)",
 'cast320_00_c': "'experimentation stage' -> 'the stage' (term kept in sibling captions)",
 'item4_04_01_c': "'particularly' softener",
 'item5_37_01_c': "'particularly' softener",
 'item5_02_01_c': "execution left unattributed in sentence 1 (named in sentence 2)",
 'cast205_01_c': "'sent' (dispatch nuance)",
}

_EN = '–'  # en-dash, confirmed rendering in this engine

CONDENSED = {
 # ---- cast -----------------------------------------------------------------
 'cast032_00_c': "A judicial assistant. The Supreme Court forbids women, so today I'm a lawyer disguised as a male student.",
 'cast040_00_c': "An extraordinary girl living with Mr Sholmes – medical degree, and popular stories in a prominent magazine.",
 'cast040_01_c': "An extraordinary girl living with Mr Sholmes – medical degree, and popular stories in a prominent magazine.",
 'cast052_00_c': "A mostly reformed pickpocket turned self-appointed 'detective inspector', making waves in her apprenticeship.",
 'cast060_00_c': "A prosecutor dubbed the Reaper of the Bailey. The souls he prosecutes are supposedly damned, one way or another.",
 'cast060_01_c': "A prosecutor dubbed the Reaper of the Bailey. The souls he prosecutes are supposedly damned, one way or another.",
 'cast070_00_c': "Scotland Yard's lead detective inspector on the case. Stern, single-minded, and a great lover of fish and chips.",
 'cast070_02_c': "Scotland Yard's lead detective inspector on the case. Stern, single-minded, and a great lover of fish and chips.",
 'cast101_00_c': "A professor at Imperial Yumei University, an authority in forensic medicine in charge of its laboratory. He's my father.",
 'cast103_00_c': "The Lord Chief Justice wields absolute authority in judicial matters, even appointing lawyers. Very intimidating.",
 'cast104_00_c': "My best friend, my father's laboratory assistant at Imperial Yumei University. The defendant in this case.",
 'cast104_01_c': "My father's laboratory assistant, my best friend. She considers herself indebted to the late Dr John Wilson.",
 'cast160_00_c': "My best friend, who I believed dead. He somehow lost his memory, and now prosecutes in the British courts.",
 'cast162_00_c': "An important Japanese man and a judge of the Supreme Court of Judicature. He once acquitted me of murder.",
 'cast162_01_c': "Japan's Minister of Foreign Affairs and judge of its Supreme Court of Judicature. He acquitted me of murder.",
 'cast200_00_c': "The lead prosecutor in this case. He seems unsettled by the turbulent changes of Japan's new Meiji era.",
 'cast201_00_c': "The victim, a former British exchange student, found guilty nine months ago of murdering Dr John Wilson.",
 'cast202_00_c': "An Imperial Police Bureau chief inspector, submerged in the sea to watch Miss Brett. He was present at her murder.",
 'cast205_01_c': "A Japanese scholar in London to research English. Acquitted of one serious crime, he's now accused of another.",
 'cast206_00_c': "A retired army man, landlord of Mr Natsume's lodgings. An old knee injury confines him to a chair most of the time.",
 'cast208_00_c': "An art student aspiring to be an artist. She's just come round after days comatose from a stab wound to the back.",
 'cast210_00_c': "A Shoyu News journalist who follows Soseki-san everywhere. As a result, he's an eyewitness to the incident.",
 'cast217_00_c': "Wife of the Altamont Gas Company's owner. A staunch believer in gas's superiority, unforgiving of its theft.",
 'cast230_00_c': "His super-high-voltage instantaneous kinesis machine exploded in use, and he now stands accused of murder.",
 'cast230_01_c': "Inventor of the kinesis machine and defendant of this case. Apparently a friend of Lord van Zieks.",
 'cast231_00_c': "A trickster who seems both engineer and magician. He built Professor Harebrayne's demonstration machine.",
 'cast255_00_c': "A visiting student to Britain, back home after bad luck with the law. Now a successful author – and a witness.",
 'cast320_00_c': "The impresario of pleasure voyages in flying balloons. Those above the stage were all his.",
 'cast321_00_c': "A young prince of Bohemia with an excessively long name. He witnessed the explosion at the Great Exhibition.",
 'cast322_00_c': "Proprietress of the Madame Tusspells Museum of Waxwork – heir to its secret art of perfect likenesses.",
 'cast324_00_c': "The fraudster behind the Red-Headed League swindle, caught by Mr Sholmes. He's of French aristocracy, it seems.",
 'cast326_00_c': "Governor of Barclay Prison. It seems he and Professor Mikotoba were friends during the latter's studies in Britain.",
 'cast560_01_c': "A financier who perished in the Great Exhibition explosion. It seems he also led a criminal organisation.",
 'cast560_02_c': "He perished in the stage explosion. Professor Harebrayne's backer – and a criminal organisation's boss.",
 'cast900_00_c': "A visiting professor of forensic medicine invited by my father. Very sadly, he was murdered eight months ago.",
 # ---- item1 ----------------------------------------------------------------
 'item1_01_01_c': "Time of death just after 2 p.m., believed due to a knife blade's trauma to the lung. Only a single wound was identified.",
 'item1_03_01_c': "An article about poison stolen from a Yumei University laboratory. Even my father, its head, knew nothing of it.",
 'item1_03_02_c': "An article on the stolen Yumei University poison. Reporter Menimemo-san got the story by eavesdropping.",
 'item1_04_04_c': "A fountain pen bearing the initials 'R. M.', with a small reservoir for drawing up ink. A little liquid remains inside.",
 'item1_04_05_c': "A fountain pen bearing the initials 'R. M.' and an emblem of some sort. A little liquid remains in the ink reservoir.",
 'item1_07_01_c': "A photograph taken by police just after the incident. The stab wound in the victim's back is clearly visible.",
 'item1_10_01_c': "An indicator solution for the poison my father's team is developing. Made in secrecy, it exists only in his laboratory.",
 # ---- item2 ----------------------------------------------------------------
 'item2_01_01_c': "Mr Natsume's receipt for books from a secondhand bookshop, submitted as evidence in the recent trial.",
 'item2_02_01_c': "A street map of Mr Natsume's neighbourhood. Submitted as evidence in the trial the other day.",
 'item2_08_02_c': "A ripped piece of envelope found in Mr Shamspeare's room. It fits perfectly with one in Miss Green's possession.",
 'item2_09_01_c': "Instructions to meet someone claiming to know about Duncan Ross, in an envelope ripped open rather roughly.",
 'item2_09_02_c': "A note in a roughly ripped-open envelope, which fits perfectly with a torn-off piece found at the crime scene.",
 'item2_13_03_c': "A cheap bar of soap from outside Mr Shamspeare's window. Its reddish medallion has mysteriously vanished.",
 'item2_13_04_c': "A cheap bar of soap from outside Mr Shamspeare's window, one surface bearing a central two-centimetre dent.",
 'item2_13_05_c': "A cheap bar of soap from outside Mr Shamspeare's window, one surface bearing a central two-centimetre dent.",
 'item2_15_01_c': "A meter dispensing gas for a set time per coin. Its very strong lock was developed with Mr Shamspeare in mind.",
 'item2_15_02_c': "A meter dispensing gas for a set time per coin. The coin box sports a very strong lock " + _EN + " and a tiny hole in its base.",
 'item2_18_01_c': "A photograph of the scene taken by police on arrival. The victim sits unconscious at the table, having been poisoned.",
 'item2_19_01_c': "A report by Scotland Yard's medical officer. It obviously mentions the poison, and details from the investigation.",
 'item2_25_01_c': "Handprints on the wall, found with the Skin Print Seeker gun. Several lie on either side of a hanging picture.",
 'item2_26_01_c': "An article about Selden, a criminal sentenced to death. He died of illness in prison, his loot undiscovered.",
 'item2_27_01_c': "Scotland Yard's file on the convict Selden, including the newspaper article about his death from illness in prison.",
 # ---- item3 ----------------------------------------------------------------
 'item3_01_01_c': "A newspaper full of articles on the world-leading science and technology at the Great Exhibition in London.",
 'item3_04_01_c': "A torn piece of rubber-backed, canvas-like material from under the experimentation stage. Its edges are scorched.",
 'item3_05_01_c': "A very curious device found behind a tree under the experimentation stage, as if hidden there deliberately.",
 'item3_05_02_c': "A weapon hidden behind a tree under the experimentation stage. It turns out to be a folding crossbow.",
 'item3_06_01_c': "Professor Harebrayne's trusty screwdriver 'Andrew'. Blood marks the tip, which matches the victim's wound.",
 'item3_06_02_c': "A metal screwdriver poking through the grille in the kinesis machine's remains. Its handle is very distinctive.",
 'item3_09_01_c': "A photograph of the victim, ostensibly 'beamed' to the Crystal Tower. An apparent stab wound marks the chest.",
 'item3_11_01_c': "Mr Asman's autopsy report. His neck broke in a violent fall, and he was stabbed in the chest with a sharp object.",
 'item3_12_01_c': "A photograph Gotts took from his balloon, showing another balloon he claims was green and exploded moments later.",
 'item3_15_01_c': "The cage from Professor Harebrayne's experiment. It crashed into the Crystal Tower with the victim inside.",
 'item3_15_02_c': "The wooden cage used for the demonstration. It crashed, victim inside, into the Crystal Tower, damaging its base.",
 'item3_17_01_c': "A fragment of unusually thick glass from the Professor waxwork's clothing, seemingly from the Crystal Tower.",
 'item3_18_02_1_c': "The camera from a waxwork in the Madame Tusspells Special Exhibit. The extended lens shows stains on the bellows.",
 'item3_18_02_c': "The camera from Mr Drebber's waxwork in the Special Exhibit. The extended lens shows stains on the bellows.",
 'item3_18_04_c': "The actual camera Mr Drebber had in the cemetery ten years ago. Extending the lens reveals dark staining on the bellows.",
 'item3_19_01_c': "A photograph of the engineer, Mr Enoch Drebber. Hard to make out, but he appears to wear a black-glass monocle.",
 'item3_21_01_c': "A Royal Society trophy for excellence in science, found in Mr Drebber's workshop – prestigious for one so young.",
 'item3_28_01_c': "A photograph of the experimentation stage after a time bomb levelled it, its metal floor blown open by the blast.",
 'item3_32_01_c': "An article on an eyewitness's tale of the Professor's alleged 'resurrection' from his grave the night of his execution.",
 # ---- item4 ----------------------------------------------------------------
 'item4_02_02_c': "A note introducing us from Professor Mikotoba to Governor Caidin, written on the back of a steamship ticket.",
 'item4_04_01_c': "A photograph from Mrs Vigil to help find her husband. He appears to have no distinctive features.",
 'item4_07_02_c': "A model of a British policeman from the Fresno Street crime scene. A twist pops a key-like shaft out from the base.",
 'item4_09_01_c': "A candelabrum from the room where the inspector was found dead. One candle's top appears to have been blown off.",
 'item4_12_02_c': "An old photograph displayed prominently in Inspector Gregson's office. On the left is Lord Klint van Zieks.",
 'item4_16_02_c': "A noticeboard covered in notes and articles on the Reaper's victims. A bloody handprint marks the back.",
 'item4_18_01_c': "A photograph of the victim, Inspector Gregson. His body appears tightly curled up, and a red hairpiece sits on his head.",
 'item4_20_01_c': "Inspector Gregson's pocket watch, wound without fail every day. No longer ticking, its face glass cracked.",
 # ---- item5 ----------------------------------------------------------------
 'item5_02_01_c': "Mr Vigil claims this will vanished after the execution. Asogi apparently called it 'the only weapon I have left'.",
 'item5_02_02_c': "Genshin Asogi's will, which Mr Vigil claims disappeared after the execution. It seems there was a third page.",
 'item5_05_01_c': "A passport in Inspector Gregson's possession, issued for France the day before his body was discovered.",
 'item5_06_02_c': "Autopsy of the Professor's final victim. Dr John H. Wilson performed and signed it, yet Professor Mikotoba wrote it.",
 'item5_12_01_c': "A telegram from Inspector Hosonaga in Japan, detailing the one he found by stealing into Judge Jigoku's office.",
 'item5_13_02_c': "A part Mr Sholmes found in Judge Jigoku's cabin: the missing 'crown' of Inspector Gregson's pocket watch.",
 'item5_14_01_c': "Genshin Asogi's ring, found in Lord Klint van Zieks's stomach at autopsy. Its claws could leave a nasty scratch.",
 'item5_15_01_c': "Lord Klint van Zieks's will, hidden in the great sword Karuma for years. A trump card left by Genshin Asogi.",
 'item5_17_01_c': "Notice of a practice evacuation by the SS Grouse's crew the night before reaching Dover. Found in Judge Jigoku's cabin.",
 'item5_18_01_c': "Taken in the Great Waterloo Hotel foyer on the morning Professor Mikotoba and Judge Jigoku arrived in London.",
 'item5_28_01_c': "Inspector Gregson's autopsy report. The coroner, Dr Gorey, could not accurately estimate the time of death.",
 'item5_37_01_c': "A photograph from Mrs Vigil to help find her husband. He appears to have no distinctive features.",
}
